# @plugin ExplosionRegeneration
# @version 1.4.2
# @author foncused

# Do you want blocks to regenerate in random order?
# true -> regeneration will occur in random order
# false -> regeneration will occur from bottom to top (fixes gravel, sand, etc. better)
random: true

# Speed in ticks for block regeneration
# You can change the speed in-game with /blockregenspeed <speed>
# Recommended not to put this number over 200 since it uses a running task
speed: 2

# Delay in ticks before block regeneration
delay: 0

# Which particle effect would you like to use?
# To disable a particle effect, set to an empty string ""
particle: "VILLAGER_HAPPY"

# Which sound would you like to use?
# To disable a sound effect, set to an empty string ""
sound: "ENTITY_CHICKEN_EGG"

# Should TNT be exploded in a chain reaction, similar to how it would normally?
tnt-chaining:
  enabled: false
  max-fuse-ticks: 40

# Should explosions send blocks flying through the air as a visual effect?
falling-blocks: false

# Which blocks should NOT be regenerated?
filter:
  - "FIRE"

# In which worlds should ExplosionRegeneration NOT regenerate blocks?
blacklist:
  - ""

# Should item drops from explosions be enabled?
drops:
  # Disabled by default to prevent item dupes
  enabled: false
  # Radius outward from explosion to check for item drop removal
  radius: 4.0
  # If enabled is set to true, the following items will still be removed
  # If enabled is set to false, the blacklist below is irrelevant
  blacklist:
    - "ARMOR_STAND"
    - "BARREL"
    - "BEACON"
    - "BLACK_SHULKER_BOX"
    - "BLAST_FURNACE"
    - "BLUE_SHULKER_BOX"
    - "BREWING_STAND"
    - "BROWN_SHULKER_BOX"
    - "CHEST"
    - "CHEST_MINECART"
    - "CYAN_SHULKER_BOX"
    - "DIAMOND_BLOCK"
    - "DISPENSER"
    - "DROPPER"
    - "EMERALD_BLOCK"
    - "FIRE"
    - "FURNACE"
    - "FURNACE_MINECART"
    - "GOLD_BLOCK"
    - "GRAY_SHULKER_BOX"
    - "GREEN_SHULKER_BOX"
    - "HOPPER"
    - "HOPPER_MINECART"
    - "IRON_BLOCK"
    - "ITEM_FRAME"
    - "LIGHT_BLUE_SHULKER_BOX"
    - "LIGHT_GRAY_SHULKER_BOX"
    - "LIME_SHULKER_BOX"
    - "MAGENTA_SHULKER_BOX"
    - "ORANGE_SHULKER_BOX"
    - "PINK_SHULKER_BOX"
    - "PURPLE_SHULKER_BOX"
    - "RED_SHULKER_BOX"
    - "SHULKER_BOX"
    - "SMOKER"
    - "TNT"
    - "TNT_MINECART"
    - "TRAPPED_CHEST"
    - "WHITE_SHULKER_BOX"
    - "YELLOW_SHULKER_BOX"

# Should ExplosionRegeneration honor WorldGuard's config and region flags?
# Setting this to true requires both WorldGuard and WorldEdit as dependencies
worldguard: false
